services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: ./php
            dockerfile: Dockerfile
        depends_on:
            - mysql-db
        volumes:
            - ./php/src:/var/www/html/
        ports:
            - 8090:80
    mysql-db:
        container_name: db
        build:
            context: ./mysql
            dockerfile: Dockerfile
        volumes:
            -  mysql-php:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 'rahsia'
            MYSQL_USER: 'MYSQL_USER'
            MYSQL_PASSWORD: 'rahsia'
        ports:
            - "3306:3306"
volumes:
  mysql-php: